### ISSUE TITLE
UTF8 is not right

### ISSUE THREAD

**Issue by tonnylitao** [MegaBits/SIOSocket#15]
the data send from server is 
{"name: "中"}

but client got wrong string.
[socket on:@"event" do:^(id data) {
    data[@"name"]   //is - , not 中
}];

There is something wrong when parsing data, please fix it.

**Comment by frandrzej** [comment]
Did you do anything else? I have the latest version from cocoapods (with socket.io-1.2.1.js) and there are no special characters in UTF-8 (e.g. Ł changes to A). 
Now I use pull 38 https://github.com/MegaBits/SIOSocket/pull/38/files because I need to use websocket transportation to make it work on Heroku.
