### ISSUE TITLE
Not receiving events 

### ISSUE THREAD

**Issue by Praphin** [MegaBits/SIOSocket#39]
Hi. I've cloned this project, and tried a simple test with an existing socket.io v1.2.1 server.
I've connected to the server, but can't receive any of the messages emitted by it. I tried both sending messages on the "update" event and on another custom one (which i've added a listener to in-app), but don't receive any of them. It was not receiving atleast onConnect event.

Is there anything I'm missing? Should I change anything else but the actual host?

**Comment by mfeltmann** [comment]
Had the same problem. Are you using the cocoapods version? 
It seems to differ from current master branch, so I updated the pods source file with the files from the master branch. Now it works for me.
In my case the callback contained a '-' and was pasted as-is, which seemed to lead to some issues in the deeps of objective-c. The master branch version uses a hash instead of the pasted method name and works fine – at least for me.

**Comment by Praphin** [comment]
Its problem with my porperty declaration...after fixing that it works fine..
